name: Go

on: [push]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0

      - name: Run tests
        run: go test ./...
